# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            James Kim
tagline:          'James Kim'
description:      'Log of my life journey'
url:              http://ggjkm.com/

author:
  name:           'James Kim'
  url:            http://ggjkm.com/

paginate:         2
emailme:          mailto:kkgg3781@gmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/rodroadl/ggjkm/

tags:

github_username:  rodroadl
linkedin_username: james-kim-3b70371b4


